---
name: Create Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Documentation
        run: |
          echo "Generating Documentation"
          echo "Documentation Generated"
